### ISSUE TITLE
TypeError: Iterating over key states is not supported

### ISSUE THREAD

**Issue by malespiaut** [skoolkid/pyskool#16]
Hello,

I've downloaded pyskool v1.2.1, and tried to launch it using `python back_to_skool.py` and I got the following error:

```
pygame 2.4.0 (SDL 2.28.1, Python 3.11.3)
Hello from the pygame community. https://www.pygame.org/contribute.html
Created directory '/home/malespiaut/.pyskool'
Using ini file at /tmp/tmp.4vivOIGOfX/pyskool-1.2.1/pyskool/data/pyskool.ini
Using game ini files in /tmp/tmp.4vivOIGOfX/pyskool-1.2.1/ini/back_to_skool
Using images in /tmp/tmp.4vivOIGOfX/pyskool-1.2.1/images
Using sounds in /tmp/tmp.4vivOIGOfX/pyskool-1.2.1/sounds
Using /home/malespiaut/.pyskool to save/load games
Reading /tmp/tmp.4vivOIGOfX/pyskool-1.2.1/pyskool/data/pyskool.ini
Reading /tmp/tmp.4vivOIGOfX/pyskool-1.2.1/ini/back_to_skool/command_lists.ini
Reading /tmp/tmp.4vivOIGOfX/pyskool-1.2.1/ini/back_to_skool/config.ini
Reading /tmp/tmp.4vivOIGOfX/pyskool-1.2.1/ini/back_to_skool/font.ini
Reading /tmp/tmp.4vivOIGOfX/pyskool-1.2.1/ini/back_to_skool/lessons.ini
Reading /tmp/tmp.4vivOIGOfX/pyskool-1.2.1/ini/back_to_skool/messages.ini
Reading /tmp/tmp.4vivOIGOfX/pyskool-1.2.1/ini/back_to_skool/skool.ini
Reading /tmp/tmp.4vivOIGOfX/pyskool-1.2.1/ini/back_to_skool/sprites.ini
Traceback (most recent call last):
  File "/tmp/tmp.4vivOIGOfX/pyskool-1.2.1/back_to_skool.py", line 24, in <module>
    main(os.path.abspath(os.path.dirname(__file__)))
  File "/tmp/tmp.4vivOIGOfX/pyskool-1.2.1/pyskool/run.py", line 237, in main
    game = Game(pyskool_ini, images_dir, sounds_dir, ini_dir, options, version, sav_file)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/tmp.4vivOIGOfX/pyskool-1.2.1/pyskool/game.py", line 125, in __init__
    self.keyboard = Keyboard()
                    ^^^^^^^^^^
  File "/tmp/tmp.4vivOIGOfX/pyskool-1.2.1/pyskool/input.py", line 27, in __init__
    self.pump()
  File "/tmp/tmp.4vivOIGOfX/pyskool-1.2.1/pyskool/input.py", line 41, in pump
    self.pressed_keys = list(pygame.key.get_pressed())
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Iterating over key states is not supported
```

**Comment by skoolkid** [comment]
Yes, Pyskool was developed against Pygame v1, and doesn't work with Pygame v2. However, there is a [pygame2](https://github.com/skoolkid/pyskool/tree/pygame2) branch on this repo that addresses the key states issue specifically. Try downloading that branch and see how it goes.

**Comment by malespiaut** [comment]
The `pygame2` branch seems to work fine. My bad! Thank you very much for your answer.
